enableStrictSsl: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.8.3.cjs

npmScopes:
  shomaya-app:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: "${NPM_GITHUB_TOKEN}"
