<template>
  <PartsPageTitle
    title="Focus Areas"
    subtitle="Our focus areas as a consulting and trading company in Bangladesh"
  />

  <div class="mx-auto flex max-w-[768px] flex-col gap-[40px] px-[20px]">
    <div>
      <h2 class="pc:text-[3rem] text-[1.6rem] font-bold">
        Focus Areas (Priority Social Issues)
      </h2>
      <p class="pc:text-[1.8rem] mt-[10px] text-[1.4rem]">
        Specific challenges faced by Bangladesh and potential areas where our
        company, along with Japanese and Bangladeshi companies, can contribute.
      </p>
    </div>

    <div v-for="(item, index) in focusAreas" :key="index" class="mb-[20px]">
      <h3 class="pc:text-[2rem] text-[1.6rem] font-bold">{{ item.title }}</h3>
      <ul class="list-disc pl-[20px]">
        <li
          v-for="description in item.descriptions"
          :key="description.text"
          class="pc:text-[1.6rem] mt-[10px] text-[1.4rem]"
        >
          {{ description.text }}
        </li>
      </ul>
    </div>
  </div>
</template>

<script setup lang="ts">
type focusArea = {
  title: string
  descriptions: { text: string }[]
}

const focusAreas: focusArea[] = [
  {
    title: 'Medical, Public Health, and Healthcare Sector',
    descriptions: [
      { text: 'Prevention of infectious diseases, including dengue fever' },
      {
        text: 'Addressing the leading cause of death—cerebrovascular diseases (cerebral infarction, cerebral hemorrhage, and subarachnoid hemorrhage)—in collaboration with hospitals and pharmaceutical companies'
      },
      {
        text: 'Prevention of the rapidly increasing number of diabetes patients and raising awareness about blood sugar spikes'
      }
    ]
  },
  {
    title: 'Environment and Circular Economy Sector',
    descriptions: [
      {
        text: 'Reducing environmental impact through upcycling and recycling initiatives for waste generated by garment factories and jute materials'
      },
      {
        text: 'Technical support for improving wastewater treatment at leather factories'
      },
      { text: 'Restoration of river pollution' },
      { text: 'Support for proper treatment and management of medical waste' }
    ]
  },
  {
    title: 'Human Resource Development and Education Sector',
    descriptions: [
      {
        text: 'Support for training automobile mechanics, care workers, and Japanese language schools'
      }
    ]
  }
]
</script>
