name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4.3.1
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 20.19.6

      - name: Enable Corepack (Yarn Berry)
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Generate Nuxt types
        run: yarn nuxt prepare

      - name: Get changed Vue / TypeScript files
        id: changed-files
        uses: tj-actions/changed-files@v47.0.6
        with:
          files: |
            **/*.vue
            **/*.ts

      - name: Run ESLint on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: yarn eslint ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Run TypeScript type check
        run: yarn typecheck
